config/routes.rb
Rails.application.routes.draw do

resources :order_checkouts

resources :main_categories do
  resources :main_category_pics
end
  

resources :main_categories do
  resources :items do 
    resources :item_pics
  end 
end

  

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
 

  devise_for :users
   resources :users#, only: [:update]

  
  get 'about' => 'welcome#about'
  
  root to: 'main_categories#index'

get "checkout", to: "items#checkout"

get "purchases", to: "order_checkouts#purchases"
get "thank_you", to: "order_checkouts#thank_you"
get "seeds", to: "order_items#seeds"
post "paypal", to: "order_checkouts#pal_purchase"
post "pal_return", to: "order_checkouts#pal_return"
get "contact", to: "welcome#contact"

end

app/models/checkout_paid_item.rb
class CheckoutPaidItem < ActiveRecord::Base
  belongs_to :order_checkout
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :main_category
  has_many :item_pics, dependent: :destroy
  has_many :order_items, dependent: :destroy
  default_scope { where(active: true) }
end

app/models/item_pic.rb
class ItemPic < ActiveRecord::Base
  belongs_to :item
  mount_uploader :pic_url, PicUploader
  serialize :description
  
  rescue ActiveMerchant::ActiveMerchantError => e
  self.description        = {}
  
end
#ItemPic.where(name:"template").last.description['Build']

app/models/main_category.rb
class MainCategory < ActiveRecord::Base
  has_many :main_category_pics, dependent: :destroy

  has_many :items, dependent: :destroy
  

end

app/models/main_category_pic.rb
class MainCategoryPic < ActiveRecord::Base
  belongs_to :main_category
  mount_uploader :pic_url, PicUploader
    serialize :description
  
  #rescue ActiveMerchant::ActiveMerchantError => e
  #self.description        = {}
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  has_many :order_checkouts
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_checkout.rb
class OrderCheckout < ActiveRecord::Base
  belongs_to :order
  has_many :order_checkout_transactions, dependent: :destroy
  has_many :checkout_paid_items, dependent: :destroy
  attr_accessor :card_number, :card_verification
 # validate :validate_card, :on => :create
  
 
  
  def purchase(current_order, params)
    response = GATEWAY.purchase(
                                price_in_cents(current_order),
                                credit_card(params),
                                purchase_options(params)
                              )
    
    
    order_checkout_transactions.create!(:action => "purchase", :amount => price_in_cents(current_order), :response => response)
   # cart.update_attribute(:purchased_at, Time.now)  ## this needs to work but dont have a purchased_at attribute in any model
      if response.success?
    response.success?
      end
  end
  
  def price_in_cents(current_order)
    # (current_order.subtotal*100 + 400).round 
    (current_order.subtotal*100).round
  end

  private
  
  def purchase_options(params)
    {
      :ip => ip_address,
      :billing_address => {
        :name     => params[:order_checkout][:bill_name],
        :address1 => params[:order_checkout][:bill_adress],
        :city     => params[:order_checkout][:bill_city],
        :state    => params[:order_checkout][:bill_state],
        :country  => "US",
        :zip      => params[:order_checkout][:bill_zip]
      }
    }
  end

  
  def credit_card(params)
        logger.debug puts "
                      debbuger
                      \n #{  }
                    
                      " 
               # exit
     if Rails.env.production?
   
          @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:params[:order_checkout]["card_expires_on(1i)"],
                verification_value: params[:order_checkout][:card_verification]   )
       else
           @credit_card ||= ActiveMerchant::Billing::CreditCard.new(

                first_name: params[:order_checkout][:first_name],
                last_name:params[:order_checkout][:last_name],
                number: params[:order_checkout][:card_number] == '' ? ENV['PAYPAL_CARD_NUMBER'] : params[:order_checkout][:card_number],
                month: params[:order_checkout]["card_expires_on(2i)"],
                year:'2020',
                verification_value: '345'   )
     end
       
  end
  
  
  
  
  
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :item_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
          :validatable, 
          :confirmable
 
  
   def admin?
   role == 'admin'
 end
 
 def moderator?
   role == 'moderator'
 end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js
  def index
    @items = Item.all
    @order_item = current_order.order_items.new
  end

  def show
  end

  def new
  end
  
  def create
 
    @item = MainCategory.find(params[:main_category_id]).items.create(params.require(:item).permit(:title, :body, :name, :price, :quantity))
    @item_id = @item.id
    redirect_to main_category_item_path(@item.main_category_id,@item.id)
  end

  def edit
  end
  
  def update
    
    Item.find(params[:id]).update_attributes(params.require(:item).permit(:title, :body, :name, :price, :quantity) )
    redirect_to main_category_item_path(Item.find(params[:id]).main_category_id, Item.find(params[:id]).id )
  end

  def destroy
    if Item.find(params[:id]).destroy
    flash[:notice] = 'An Item was destoryed'
    end
    redirect_to root_path
  end  
  
  def checkout
    render  "items/checkout"
  end
  
  
  
end

app/controllers/main_categories_controller.rb
class MainCategoriesController < ApplicationController

  def index

  end

  def show
   
  end
  
  def create
    MainCategory.create(params.require(:main_category).permit(:title,:body,:template ) )
   # MainCategory.create(title: "test" ,body: params.inspect )
    redirect_to main_categories_path
  end

  def new
    
  end
  

  def edit
    
  end
  
  def update
    MainCategory.find(params[:id]).update_attributes(params.require(:main_category).permit(:title, :body) )
    redirect_to main_category_path(params[:id])
  end
  
  def destroy
    if MainCategory.find(params[:id]).destroy
    flash[:notice] = 'A Category was destoryed'
    end
    redirect_to root_path
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/item_pics_helper.rb
module ItemPicsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_categories_helper.rb
module MainCategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/main_categories/edit.html.erb
<%if $admin%>
<% @MCategory = MainCategory.find(params[:id])%>
<%= form_for @MCategory, :url => {:controller => 'main_categories', :action => 'update',  :method => 'post'} do |f| %>
<%= f.label :title%>
<%= f.text_field :title, class: 'form-control', placeholder: '' %>
<%= f.label :body %>
<%= f.text_area :body, rows: 4, class: 'form-control', placeholder: "Enter post body" %>
<%= f.submit "Save", class: 'btn btn-success' %>

<%end%>
<br>
<p>Click on Picture to Edit Picture</p>
<%if @MCategory.main_category_pics.first%>
      <%@MCategory.main_category_pics.each do |pic|%>
        <%= link_to edit_main_category_main_category_pic_path(@MCategory.id, pic.id) do%>
       <img src="<%= pic.pic_url_url%>" style='height:100px; width:100px;'>
      <%end%>
  <%end%>
<%end%>




<br><br><button><%= link_to 'Add New Pic to Category', new_main_category_main_category_pic_path(params[:id])%></button><br><br>
<%= link_to "Delete Category", [MainCategory.find(params[:id])], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Category?' } %>
<%end%>

app/views/main_categories/factory.js.erb
function Image($rootScope) {
                               var Image = { 
                                            logo: "https://s3-us-west-2.amazonaws.com/pics120/migtech+store/main_categories/index/A-Many-CellPhones.jpg", 
                                            logoN: "https://s3-us-west-2.amazonaws.com/pics120/migtech+store/main_categories/index/logot.png"
                                           };
                                   
                                return Image;
                            };
function Items($rootScope) {
                               var Items =  <%=raw JSON.pretty_generate(Item.all.as_json)%>
                                   
                                return Items;
                            }; 

app/views/main_categories/index.html.erb
<style >
  .seebox1 {
            outline:dotted;
            
          }
  

</style>


<div class="col-1"></div>

<div class="col-10  height" id="logo" style='background-image:url("https://s3-us-west-2.amazonaws.com/pics120/migtech+store/main_categories/index/A-Many-CellPhones.jpg")'>
    <img src="https://s3-us-west-2.amazonaws.com/pics120/migtech+store/main_categories/index/logot.png" id="logoN" >
</div>

<div class="col-1"></div>



<%if $admin %>

<%= render "main_categories/index/if_Admin" %>

<% else %>

<%= render "main_categories/index/if_Not_Admin" %>

<%end%>




      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

app/views/main_categories/index/_if_Admin.html.erb
<div class='col-12 seebox removempb '>

  
      <h1 style='text-align:center;'>Departments</h1>
      <p style='text-align:center;'><%= link_to 'Make new Department', new_main_category_path%></p>
  
</div>


    <div class="row small-up-2 large-up-4">

    


 <div class="row small-up-2 medium-up-3 large-up-4">
 <% MainCategory.all.each do |category| %>
   <%if !category.template%>
            <div class="column">
              <%= link_to main_category_path(category.id) do%>
              <%if category.main_category_pics.any?%>
                  <%pic = category.main_category_pics.first.pic_url.url%>
                  <%pic_escape = category.main_category_pics.first.urlseed%>
              <%end%>
              <img class="thumbnail" src="<%= category.main_category_pics.any? ? ((pic == nil) | (pic == "") ? pic_escape : pic) : "https://placehold.it/550x550"%>">
              <%end%>
              <h5><%= category.title%></h5><%= link_to "Edit-items", main_category_items_path(category.id)%>
              <%= link_to "Edit-department", edit_main_category_path(category.id) %>
            </div>
   <%end%>
   <%end%>
      
          </div>



 <hr>

    <div class="row column text-center">
      <h2>All Products</h2>
      <hr>
    </div>

    <div class="row small-up-2 large-up-4">
      
 
      
   <% Item.all.each do |item|%>
       


      <div class="column">
        <%= link_to main_category_item_path(item.main_category_id, item.id) do%>
        <div class="thumbnail vhcenterp" style="width:300px; height:400px; background-color:lightgrey; " >
          <%if item.item_pics.any?%>
          <%pic = item.item_pics.first.pic_url.url%>
          <%picseed = item.item_pics.first.urlseed%>
          <%end%>
         <img class="thumbnail vhcenters" src="<%= item.item_pics.first ? (pic == nil ? picseed : pic) : "https://placehold.it/300x400" %>" style="hieght:400px;">
        </div>
        <%end%>
        <h5><%= item.name %></h5>
        <p><%= number_to_currency(item.price)%></p>
        <%= form_for current_order.order_items.new, remote: true do |f| %>
        <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.submit "Add to Cart", class: "button expanded" %>
        <% end %>
        
      </div> 

              

       
<%end%> 
   
    </div>

   
      <hr>
      <ul class="menu">
       
         <li>
          <%= link_to root_path do%>
          <p style="color:white;">Home</p>
          <%end%>
        </li>
        <li>
          <%= link_to about_path do%>
          <p style="color:white;">About</p>
          <%end%>
        </li>
        <li>
          <%= link_to contact_path do%>
          <p style="color:white;">Contact</p>
          <%end%>
        </li>
        <li class="float-right" style="float:right;">Copyright 2016</li>
      </ul>
    


<hr>

      <h1>Templates</h1>

      <br>
      <% MainCategory.all.each do |category|%>
            <%if category.template%>
               <h3><%= link_to category.title, main_category_items_path(category.id)%></h3>
               <p><%= category.body%></p>
               <%if category.main_category_pics.first%>
                 <%pic = category.main_category_pics.first.pic_url.url%>
                 <%pic_escape = category.main_category_pics.first.urlseed%>
                  <img src="<%= (pic == nil) | (pic == "") ? pic_escape : pic%>" style='height:100px; width:100px;'>
               <%end%>
              <br><button><%= link_to "Edit This Category", edit_main_category_path(category.id) %></button>
          <%end%>
      <%end%>
      <br>
      <br>
     
      <br><br><br><br>

</div>

app/views/main_categories/index/_if_Not_Admin.html.erb
<div class='col-12 seebox removempb '>

  
      <h1 style='text-align:center;'>Departments</h1>
      
  
</div>


    <div class="row small-up-2 large-up-4">

    


 <div class="row small-up-2 medium-up-3 large-up-4">
   <% MainCategory.all.each do |category|%>
   <%if !category.template%>
            <div class="column">
               
              <%= link_to main_category_path(category.id) do%>
              <%if category.main_category_pics.any?%>
              <%pic = category.main_category_pics.first.pic_url.url%>
              <%pic_escape = category.main_category_pics.first.urlseed%>
              <%end%>
              <img class="thumbnail" src="<%= category.main_category_pics.any? ? ((pic == nil) | (pic == "") ? pic_escape : pic) : "https://placehold.it/550x550"%>">
              <%end%>
              <h5><%= category.title%></h5>
            </div>
   <%end%>
   <%end%>
      
          </div>


 <hr>

    <div class="row column text-center">
      <h2>All Products</h2>
      <hr>
    </div>

    <div class="row small-up-2 large-up-4">
      
 
      
   <% Item.all.each do |item|%>
       


      <div class="column">
        <%= link_to main_category_item_path(item.main_category_id, item.id) do%>
        <div class="thumbnail vhcenterp" style="width:300px; height:400px; background-color:lightgrey; " >
          <%if item.item_pics.any?%>
          <%pic = item.item_pics.first.pic_url.url%>
          <%picseed = item.item_pics.first.urlseed%>
          <%end%>
         <img class="thumbnail vhcenters" src="<%= item.item_pics.first ? (pic == nil ? picseed : pic) : "https://placehold.it/300x400" %>" style="hieght:400px;">
        </div>
        <%end%>
        <h5><%= item.name %></h5>
        <p><%= number_to_currency(item.price)%></p>
        <%= form_for current_order.order_items.new, remote: true do |f| %>
        <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.submit "Add to Cart", class: "button expanded" %>
        <% end %>
        
      </div> 

                <% if $admin%>
                    <br><button><%= link_to "Edit This Category", edit_main_category_path(category.id) %></button>
                <%end%>

       
<%end%> 
   
    </div>

   
      <hr>
      <ul class="menu">
       
         <li>
          <%= link_to root_path do%>
          <p style="color:white;">Home</p>
                              <%end%>
        </li>
        <li>
          <%= link_to about_path do%>
          <p style="color:white;">About</p>
                                <%end%>
        </li>
        <li>
          <%= link_to contact_path do%>
          <p style="color:white;">Contact</p>
                                  <%end%>
        </li>
        <li class="float-right" style="float:right;">Copyright 2016</li>
      </ul>
    

app/views/main_categories/new.html.erb
<%if $admin%>
<h1>Create New Categroy</h1>

<br>
<%= form_for MainCategory.new, :url => {:controller => 'main_categories', :action => 'create',  :method => 'post'} do |f|%>
<br><%= f.label :title%>
<br><%= f.text_field :title, class: 'form-control', placeholder: "Enter A Title" %>
<%= f.label :body %>
<%= f.text_area :body, rows: 5, class: 'form-control', placeholder: "Enter description" %>
<%= f.label "Template?" %>
<%= f.check_box :template, {}, true, false %> <br />

<%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>

<%end%>

app/views/main_categories/show.html.erb
<%@items = MainCategory.find(params[:id]).items%>
<%if @items.any?%>
<%@items.each do |item|%>
<% if item.item_pics.any?%>
<%pic = item.item_pics.first.pic_url.url%>
<%pic_seed = item.item_pics.first.urlseed%>
<%end%>
 
 <div class="row column text-center">
      <h2><%=MainCategory.find(params[:id]).title%></h2>
      <hr>
    </div>

    <div class="row small-up-2 large-up-4">
      
 
      
 
       


      <div class="column">
        <%= link_to main_category_item_path(item.main_category_id, item.id) do%>
        <div class="thumbnail vhcenterp" style="width:300px; height:400px; background-color:lightgrey; " >
          <%if item.item_pics.any?%>
          <%pic = item.item_pics.first.pic_url.url%>
          <%picseed = item.item_pics.first.urlseed%>
          <%end%>
         <img class="thumbnail vhcenters" src="<%= item.item_pics.first ? (pic == nil ? picseed : pic) : "https://placehold.it/300x400" %>" style="hieght:400px;">
        </div>
        <%end%>
        <h5><%= item.name %></h5>
        <p><%= number_to_currency(item.price)%></p>
        <%= form_for current_order.order_items.new, remote: true do |f| %>
        <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.submit "Add to Cart", class: "button expanded" %>
        <% end %>
        
      </div> 

              

       

   
    </div>



<div class="col-12" style="height:100px;"></div>
<hr>

<%end%>
<%else%>

<div class="col-12 vhcenterp seebox"  style="height:400px;">
    <div class="col-10 vhcenters seebox"><h1 class="center">We are Sorry :( But this category has no items yet.</h1>
      </div>
</div>

<%end%>